// Automatically generated file
export const imagePaths = {
  "Accomodation": [
    "/images/Accomodation/room1.jpeg",
    "/images/Accomodation/room2.jpeg",
    "/images/Accomodation/room3.jpeg",
    "/images/Accomodation/room4.jpeg",
    "/images/Accomodation/room5.jpeg",
    "/images/Accomodation/room6.jpeg",
    "/images/Accomodation/room7.jpeg",
    "/images/Accomodation/room8.jpeg",
    "/images/Accomodation/room9.jpeg",
    "/images/Accomodation/room10.jpeg"
  ],
  "Cooking": [
    "/images/Cooking/1 (1).jpeg",
    "/images/Cooking/1 (1).jpg",
    "/images/Cooking/1 (2).jpeg",
    "/images/Cooking/1 (2).jpg",
    "/images/Cooking/1 (3).jpg",
    "/images/Cooking/1 (4).jpg",
    "/images/Cooking/1 (5).jpg",
    "/images/Cooking/1 (6).jpg",
    "/images/Cooking/1 (7).jpg",
    "/images/Cooking/1 (8).jpg"
  ],
  "Experience Cinnomon and Tea": [
    "/images/Experience Cinnomon and Tea/1 (1).jpeg",
    "/images/Experience Cinnomon and Tea/1 (1).jpg",
    "/images/Experience Cinnomon and Tea/1 (10).jpeg",
    "/images/Experience Cinnomon and Tea/1 (10).jpg",
    "/images/Experience Cinnomon and Tea/1 (11).jpg",
    "/images/Experience Cinnomon and Tea/1 (12).jpg",
    "/images/Experience Cinnomon and Tea/1 (13).jpg",
    "/images/Experience Cinnomon and Tea/1 (14).jpg",
    "/images/Experience Cinnomon and Tea/1 (15).jpg",
    "/images/Experience Cinnomon and Tea/1 (16).jpg",
    "/images/Experience Cinnomon and Tea/1 (17).jpg",
    "/images/Experience Cinnomon and Tea/1 (18).jpg",
    "/images/Experience Cinnomon and Tea/1 (19).jpg",
    "/images/Experience Cinnomon and Tea/1 (2).jpeg",
    "/images/Experience Cinnomon and Tea/1 (2).jpg",
    "/images/Experience Cinnomon and Tea/1 (20).jpg",
    "/images/Experience Cinnomon and Tea/1 (21).jpg",
    "/images/Experience Cinnomon and Tea/1 (22).jpg",
    "/images/Experience Cinnomon and Tea/1 (23).jpg",
    "/images/Experience Cinnomon and Tea/1 (24).jpg",
    "/images/Experience Cinnomon and Tea/1 (25).jpg",
    "/images/Experience Cinnomon and Tea/1 (26).jpg",
    "/images/Experience Cinnomon and Tea/1 (27).jpg",
    "/images/Experience Cinnomon and Tea/1 (28).jpg",
    "/images/Experience Cinnomon and Tea/1 (3).jpeg",
    "/images/Experience Cinnomon and Tea/1 (3).jpg",
    "/images/Experience Cinnomon and Tea/1 (4).jpeg",
    "/images/Experience Cinnomon and Tea/1 (4).jpg",
    "/images/Experience Cinnomon and Tea/1 (5).jpeg",
    "/images/Experience Cinnomon and Tea/1 (5).jpg",
    "/images/Experience Cinnomon and Tea/1 (6).jpeg",
    "/images/Experience Cinnomon and Tea/1 (6).jpg",
    "/images/Experience Cinnomon and Tea/1 (7).jpeg",
    "/images/Experience Cinnomon and Tea/1 (7).jpg",
    "/images/Experience Cinnomon and Tea/1 (8).jpeg",
    "/images/Experience Cinnomon and Tea/1 (8).jpg",
    "/images/Experience Cinnomon and Tea/1 (9).jpeg",
    "/images/Experience Cinnomon and Tea/1 (9).jpg"
  ],
  "Volunteering": [
    "/images/Volunteering/1 (1).jpeg",
    "/images/Volunteering/1 (1).jpg",
    "/images/Volunteering/1 (10).jpg",
    "/images/Volunteering/1 (11).jpg",
    "/images/Volunteering/1 (12).jpg",
    "/images/Volunteering/1 (13).jpg",
    "/images/Volunteering/1 (14).jpg",
    "/images/Volunteering/1 (15).jpg",
    "/images/Volunteering/1 (16).jpg",
    "/images/Volunteering/1 (17).jpg",
    "/images/Volunteering/1 (18).jpg",
    "/images/Volunteering/1 (19).jpg",
    "/images/Volunteering/1 (2).jpeg",
    "/images/Volunteering/1 (2).jpg",
    "/images/Volunteering/1 (3).jpg",
    "/images/Volunteering/1 (4).jpg",
    "/images/Volunteering/1 (5).jpg",
    "/images/Volunteering/1 (6).jpg",
    "/images/Volunteering/1 (7).jpg",
    "/images/Volunteering/1 (8).jpg",
    "/images/Volunteering/1 (9).jpg"
  ]
};
